+define+S50 
+define+VERBOSE 
+incdir+../../rtl/core 
+incdir+../tb/
../tb/sdram_interterface.sv
../tb/wb_interface.sv
../tb/diffBankAndRowStimulus.sv
../tb/sdrc_interface.sv
../tb/sdrc_scoreboard.sv
../tb/sdrc_monitor.sv
../tb/addressStimulus.sv
../tb/sdrc_driver.sv
../tb/sdrc_environment.sv
../tb/sdrc_environment2.sv
../tb/Test_proyecto2.sv
../tb/whitebox_interface.sv
../tb/assertions.sv
../tb/Clocks.sv
../tb/tb_top_proyecto2_test.sv
../model/mt48lc2m32b2.v
../model/mt48lc8m8a2.v
../model/IS42VM16400K.V
../../rtl/top/sdrc_top.v 
../../rtl/wb2sdrc/wb2sdrc.v 
../../rtl/lib/async_fifo.v  
../../rtl/core/sdrc_core.v 
../../rtl/core/sdrc_bank_ctl.v 
../../rtl/core/sdrc_bank_fsm.v 
../../rtl/core/sdrc_bs_convert.v 
../../rtl/core/sdrc_req_gen.v 
../../rtl/core/sdrc_xfr_ctl.v 

